# Assignment 1 - NumPy: Fundamentals, Operations & Broadcasting
### Data Analytics in Python | Week 3, Classes 7 & 8


### Instructions

- This assignment has **four parts** and **40 questions total** (40 marks).
- Write your answer in the code cell directly below each question.
- Do **not** delete or modify the question cells.
- Use only the imports provided. Do **not** import pandas, sklearn, or scipy.
- Every answer must be a runnable Python cell - no pseudocode.
- Show all output with `print()`. Unlabelled output receives half marks.

| Part | Title | Questions | Marks |
|------|-------|-----------|-------|
| A | Array Construction & Attributes | Q1–Q10 | 10 |
| B | WHO Global Health Dataset | Q11–Q20 | 10 |
| C | Operations, Broadcasting & Linear Algebra | Q21–Q30 | 10 |
| D | Pakistan Crop Yield Dataset | Q31–Q40 | 10 |

**Total: 40 marks**

## How to install Numpy to your vscode or local environment?

In [ ]:
#write installation code here
!pip install numpy -q  # -q refers to quiet mode here

In [11]:
#RUN THIS CELL FIRST - imports and random seed
import numpy as np
import time

np.random.seed(42)   # do not change - ensures reproducible results
print('NumPy version:', np.__version__)

NumPy version: 2.3.4


## Part A - Array Construction & Attributes
*10 questions · 1 mark each*

This part tests your ability to create arrays the right way, read their metadata,
and understand the view/copy distinction - the three foundations of Class 7.

### Q1 - Five ways to create an array (1 mark)

Create **five** separate arrays using five different construction methods:

| Array | Method | Values |
|-------|--------|--------|
| `a` | `np.array()` from a Python list | `[3, 1, 4, 1, 5, 9, 2, 6]` |
| `b` | `np.arange()` | Even integers from 0 to 18 inclusive |
| `c` | `np.linspace()` | 7 evenly spaced values from 0.0 to 1.0 |
| `d` | `np.zeros()` | Shape (3, 4) with dtype `int16` |
| `e` | `np.eye()` | 5×5 identity matrix |

Print each array and its `dtype`.

In [5]:
a = np.array([3, 1, 4, 1, 5, 9, 2, 6])
b = np.arange(0, 19, 2)
c = np.linspace(0.0, 1.0, 7)
d = np.zeros((3, 4), dtype=np.int16)
e = np.eye(5)

print(f"a: {a} | dtype: {a.dtype}")
print(f"b: {b} | dtype: {b.dtype}")
print(f"c: {c} | dtype: {c.dtype}")
print(f"d:\n {d} | dtype: {d.dtype}")
print(f"e:\n {e} | dtype: {e.dtype}")

a: [3 1 4 1 5 9 2 6] | dtype: int64
b: [ 0  2  4  6  8 10 12 14 16 18] | dtype: int64
c: [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ] | dtype: float64
d:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] | dtype: int16
e:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] | dtype: float64


### Q2 - Shape, ndim, size, nbytes (1 mark)

Given the following array:
```python
data = np.random.randint(0, 100, size=(6, 8, 3))
```
Without running a loop, print:
1. print the `array` in data
2. `data.shape` and `also explain the shape in words`
3. `data.ndim`
4. `data.size` (total element count)
5. `data.nbytes` (total bytes in memory)
6. The `itemsize` of each element

Then verify: `size × itemsize == nbytes`. Print `True` or `False`.

In [12]:
# Q2 - your answer here
data = np.random.randint(0, 100, size=(6, 8, 3))

print(f"data: {data}")
print(f"shape   : {data.shape}")
print(f"ndim   : {data.ndim}")
print(f"size   : {data.size}")
print(f"nbytes   : {data.nbytes}")
print(f"itemsize   : {data.itemsize}")

print(f"size × itemsize == nbytes: {data.size * data.itemsize == data.nbytes}")

explanation = """
EXPLANATION OF OUTPUT & SHAPE (6, 8, 3):

1. Array Dimensions:
   - Axis 0 (Size 6): Outermost layer - 6 distinct 2D arrays/grids (or blocks/pages).
   - Axis 1 (Size 8): Middle layer - 8 rows inside each grid.
   - Axis 2 (Size 3): Innermost layer - 3 columns (or values) per row.

2. Bracket Breakdown:
   - The three opening brackets `[[[` at the top signal a 3D array.
   - Outermost `[`: Groups the 6 2D matrices.
   - Middle `[`: Groups the 8 rows in each matrix.
   - Innermost `[`: Groups the 3 individual values in each row.

3. How to Visualize It:
   - Think of a notebook with 6 pages, where each page has a table with 8 rows and 3 columns.
   - Alternatively, think of an RGB image: 6 pixels tall, 8 pixels wide, with 3 color channels per pixel.
"""

print(explanation)

data: [[[51 92 14]
  [71 60 20]
  [82 86 74]
  [74 87 99]
  [23  2 21]
  [52  1 87]
  [29 37  1]
  [63 59 20]]

 [[32 75 57]
  [21 88 48]
  [90 58 41]
  [91 59 79]
  [14 61 61]
  [46 61 50]
  [54 63  2]
  [50  6 20]]

 [[72 38 17]
  [ 3 88 59]
  [13  8 89]
  [52  1 83]
  [91 59 70]
  [43  7 46]
  [34 77 80]
  [35 49  3]]

 [[ 1  5 53]
  [ 3 53 92]
  [62 17 89]
  [43 33 73]
  [61 99 13]
  [94 47 14]
  [71 77 86]
  [61 39 84]]

 [[79 81 52]
  [23 25 88]
  [59 40 28]
  [14 44 64]
  [88 70  8]
  [87  0  7]
  [87 62 10]
  [80  7 34]]

 [[34 32  4]
  [40 27  6]
  [72 71 11]
  [33 32 47]
  [22 61 87]
  [36 98 43]
  [85 90 34]
  [64 98 46]]]
shape   : (6, 8, 3)
ndim   : 3
size   : 144
nbytes   : 576
itemsize   : 4
size × itemsize == nbytes: True

EXPLANATION OF OUTPUT & SHAPE (6, 8, 3):

1. Array Dimensions:
   - Axis 0 (Size 6): Outermost layer - 6 distinct 2D arrays/grids (or blocks/pages).
   - Axis 1 (Size 8): Middle layer - 8 rows inside each grid.
   - Axis 2 (Size 3): Innermost layer - 

### Q3 - dtype choice and memory (1 mark)

You are storing 10 million binary flags (values are only 0 or 1).  
Create the same array three times with different dtypes: `bool`, `int32`, `float64`.

```python
flags_raw = np.random.randint(0, 2, size=10_000_000)
```

For each dtype, print the `dtype` and `nbytes`.  
Finally, print how many times larger `float64` is compared to `bool`.
Explain in words `what is the meaning of the number at the end of these data types` int32 and int64 and float64. How are these two impact memory?

In [19]:
# Q3 - your answer here
flags_raw = np.random.randint(0, 2, size=10_000_000)        #you can just copy this line and paste 3 times, then you can add dtype = 'bool' or 'int32' or any, or you can do as below to generate the same output


# for dt in [np.bool_, np.int32, np.float64]:
#     arr = flags_raw.astype(dt)
#     print(f"dtype={str(dt.__name__):8}  nbytes={arr.nbytes:,}")

flags_bool = flags_raw.astype('bool')
flags_int32 = flags_raw.astype('int32')
flags_float64 = flags_raw.astype('float64')

print(f"boolean array: {flags_bool.dtype}, nbytes: {flags_bool.nbytes}")
print(f"int32 array: {flags_int32.dtype}, nbytes: {flags_int32.nbytes}")
print(f"float64 array: {flags_float64.dtype}, nbytes: {flags_float64.nbytes}")

ratio = flags_raw.astype(np.float64).nbytes // flags_raw.astype(np.bool_).nbytes
print(f"\nfloat64 is {ratio}× larger than bool")

boolean array: bool, nbytes: 10000000
int32 array: int32, nbytes: 40000000
float64 array: float64, nbytes: 80000000

float64 is 8× larger than bool


### Q4 - Indexing and slicing a 2D array (1 mark)

```python
exam = np.array([
    #S1  S2  S3  S4  S5  <--- Subjects
    [72, 85, 91, 68, 79],   #Student1
    [88, 54, 76, 95, 83],   #Student2
    [61, 77, 82, 70, 90],   #Student3
    [95, 88, 74, 66, 58],   #Student4
    [43, 69, 88, 92, 75],   #Student5
])  # shape (5 students, 5 subjects)
```

Using **a single indexing expression each**, extract:
1. The score of student 2 (row index 1) in subject 3 (col index 2)
2. All scores of student 4 (last-but-one row)
3. All scores in subject 1 (first column)
4. The 3×3 block in the top-left corner
5. Every other student (rows 0, 2, 4), all subjects - using step slicing

In [20]:
# Q4 - your answer here
exam = np.array([
    [72, 85, 91, 68, 79],
    [88, 54, 76, 95, 83],
    [61, 77, 82, 70, 90],
    [95, 88, 74, 66, 58],
    [43, 69, 88, 92, 75],
])


print(f"1. Student 2, Subject 3 : {exam[1, 2]}")
print(f"2. All scores of Student 4: {exam[3, :]}")
print(f"3. All scores in Subject 1 : {exam[:, 0]}")
print(f"4. Top-left 3×3 block:\n {exam[:3, :3]}")
print(f"5. Every other student (0,2,4):\n {exam[::2, :]}")


1. Student 2, Subject 3 : 76
2. All scores of Student 4: [95 88 74 66 58]
3. All scores in Subject 1 : [72 88 61 95 43]
4. Top-left 3×3 block:
 [[72 85 91]
 [88 54 76]
 [61 77 82]]
5. Every other student (0,2,4):
 [[72 85 91 68 79]
 [61 77 82 70 90]
 [43 69 88 92 75]]


### Q5 - Views vs copies (1 mark)

```python
temps = np.array([36.5, 37.2, 38.9, 36.8, 39.1, 37.5])
```

**Part A - The view trap:**  
Create `high = temps[2:5]`. Modify `high[0] = 99.0`.  
Print `temps`. Explain in a comment why `temps` changed.

**Part B - Breaking the link:**  
Reset `temps` to its original values. Now create a **genuine copy** `safe = temps[2:5].copy()`.  
Modify `safe[0] = 99.0`. Print both `temps` and `safe`.  
Explain in a comment why `temps` is unchanged this time.

**Part C - Verification:**  
Use `np.shares_memory()` to confirm Part A shares memory and Part B does not.

In [85]:
# Q5 - your answer here
temps = np.array([36.5, 37.2, 38.9, 36.8, 39.1, 37.5])

# Part A - view trap
high = temps[2:5]
print(f"\nhigh: {high} is just like a window to original array (temps).")
high[0] = 99.0
print("\nPart A - temps after modifying high(view):", temps)
# Slicing returns a VIEW sharing the same memory buffer,
# so writing to high[0] writes directly into temps[2].

# Part B - genuine copy
temps = np.array([36.5, 37.2, 38.9, 36.8, 39.1, 37.5])   # reset
safe = temps[2:5].copy()
safe[0] = 99.0
print("Part B - temps (unchanged):", temps)
print("Part B - safe (modified)  :", safe)
# .copy() allocates a new buffer; modifying safe never touches temps.

# Part C - verification
temps = np.array([36.5, 37.2, 38.9, 36.8, 39.1, 37.5])
high2 = temps[2:5]
safe2 = temps[2:5].copy()
print("Part C - high2 shares memory:", np.shares_memory(temps, high2))
print("Part C - safe2 shares memory:", np.shares_memory(temps, safe2))


high: [38.9 36.8 39.1] is just like a window to original array (temps).

Part A - temps after modifying high(view): [36.5 37.2 99.  36.8 39.1 37.5]
Part B - temps (unchanged): [36.5 37.2 38.9 36.8 39.1 37.5]
Part B - safe (modified)  : [99.  36.8 39.1]
Part C - high2 shares memory: True
Part C - safe2 shares memory: False


### Q6 - Boolean masking (1 mark)

```python
bp = np.array([118, 142, 135, 128, 155, 112, 167, 139, 121, 148])
```

Using boolean masks (no loops, no if/else), in **one expression each**:
1. Print all readings above 140 (hypertensive range)
2. Print all readings between 120 and 140 inclusive (borderline)
3. Count how many readings are below 120 (normal)
4. Replace all readings above 160 with `160` directly in the array  
   (simulate capping an impossible sensor value)
5. Print the percentage of hypertensive readings (> 140) rounded to 1 decimal place

In [86]:
# Q6 - your answer here
bp = np.array([118, 142, 135, 128, 155, 112, 167, 139, 121, 148])


print(f"1. Above 140 (hypertensive)     : {bp[bp > 140]}")
print(f"2. Between 120-140 (borderline) : {bp[(bp >= 120) & (bp <= 140)]}")
print(f"3. Count below 120 (normal)     : {(bp < 120).sum()}")

# 4. Cap values above 160 in place
bp[bp > 160] = 160
print("4. After capping >160           :", bp)

# 5. Percentage hypertensive (>140)
pct = (bp > 140).sum() / len(bp) * 100
print(f"5. Hypertensive readings: {pct:.1f}%")

1. Above 140 (hypertensive)     : [142 155 167 148]
2. Between 120-140 (borderline) : [135 128 139 121]
3. Count below 120 (normal)     : 2
4. After capping >160           : [118 142 135 128 155 112 160 139 121 148]
5. Hypertensive readings: 40.0%


### Q7 - Fancy indexing and argsort (1 mark)

```python
scores  = np.array([78, 95, 61, 88, 72, 99, 54, 83, 91, 67])
names   = np.array(['Ali','Sara','Usman','Fatima','Bilal',
                    'Ayesha','Hassan','Zara','Omar','Hina'])
```

1. Use `np.argsort()` to get the indices that would sort `scores` descending.
2. Print the top-3 students (name and score) using those indices.
3. Print the bottom-3 students (name and score).
4. Use fancy indexing to extract scores at positions `[0, 3, 5, 8]` simultaneously.
5. Using a boolean mask, print the names of all students who scored 80 or above.

In [87]:
# Q7 - your answer here
scores = np.array([78, 95, 61, 88, 72, 99, 54, 83, 91, 67])
names  = np.array(['Ali','Sara','Usman','Fatima','Bilal',
                   'Ayesha','Hassan','Zara','Omar','Hina'])

# 1. Indices that sort descending
rank_idx = np.argsort(scores)[::-1]     #argsort returns an array of indices (not values) from lowest to higest then we apply reverse indexing to get highest to lowest

print(f'\nindices of rank_idx: {rank_idx}, scores with sorted index: {scores[rank_idx]}')

# 2. Top-3
print("\nTop 3:")
for i, idx in enumerate(rank_idx[:3]):
    print(f"  {i+1}. {names[idx]:10} {scores[idx]}")

# 3. Bottom-3
print("Bottom 3:")
for i, idx in enumerate(rank_idx[-3:][::-1]):       #-3 gets last three value indices but as we know values are sorted in descending like [67 61 54], to get the this reversed we applied reverse indexing with -1 on this chunk of array 
    print(f"  {i+1}. {names[idx]:10} {scores[idx]}")

# 4. Fancy indexing
print(f"Scores at positions [0,3,5,8]: {scores[[0, 3, 5, 8]]}")

# 5. Names of students scoring ≥80
print(f"Scored 80+: {names[scores >= 80]}")


indices of rank_idx: [5 1 8 3 7 0 4 9 2 6], scores with sorted index: [99 95 91 88 83 78 72 67 61 54]

Top 3:
  1. Ayesha     99
  2. Sara       95
  3. Omar       91
Bottom 3:
  1. Hassan     54
  2. Usman      61
  3. Hina       67
Scores at positions [0,3,5,8]: [78 88 99 91]
Scored 80+: ['Sara' 'Fatima' 'Ayesha' 'Zara' 'Omar']


### Q8 - Reshaping and stacking (1 mark)

1. Create `flat = np.arange(1, 25)`.  
   Reshape it into shape (2, 3, 4) in one line. Print the result and its shape.

2. Create two (4, 3) arrays:
   ```python
   week1 = np.random.randint(60, 100, (4, 3))
   week2 = np.random.randint(60, 100, (4, 3))
   ```
   Stack them **vertically** with `np.vstack()` (result: 8×3) and  
   **horizontally** with `np.hstack()` (result: 4×6). Print both shapes.

3. Split the vertically-stacked result back into two equal arrays using `np.split()`.  
   Verify `np.array_equal(split_result[0], week1)` prints `True`.

In [88]:
# Q8 - your answer here
np.random.seed(42)
week1 = np.random.randint(60, 100, (4, 3))
week2 = np.random.randint(60, 100, (4, 3))

#1. Reshape
flat = np.arange(1, 25)
cube = flat.reshape(2, 3, 4)
print(f"Reshaped to (2,3,4):\n {cube}, \nshape: {cube.shape}")

#2. Stack
vstacked = np.vstack([week1, week2])
hstacked = np.hstack([week1, week2])
print(f"\nvstack shape: {vstacked.shape}")
print(f"hstack shape: {hstacked.shape}")

#3. Split back and verify
halves = np.split(vstacked, 2, axis=0)
print(f"Split result[0] == week1: {np.array_equal(halves[0], week1)}")

Reshaped to (2,3,4):
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], 
shape: (2, 3, 4)

vstack shape: (8, 3)
hstack shape: (4, 6)
Split result[0] == week1: True


### Q9 - Speed: NumPy vs Python loop (1 mark)

Compute the **sum of squares** of 5,000,000 numbers using:

**Method A - Python loop:**
```python
nums = list(range(1, 5_000_001))
```
Loop through `nums` and accumulate `total += x**2`.

**Method B - NumPy vectorised:**
```python
arr = np.arange(1, 5_000_001)
```
Compute `(arr**2).sum()` in a single expression.

Time both with `time.time()`. Print:
- Time for each method (in milliseconds, 2 decimal places (`round()`))
- The speedup factor (loop_time / numpy_time, integer)
- Confirm both methods give the same answer

In [89]:
# Q9 - your answer here
import time

# Method A - Python loop
nums = list(range(1, 5_000_001))
t0 = time.time()
total_loop = 0
for x in nums:
    total_loop += x ** 2
t_loop = (time.time() - t0) * 1000

# Method B - NumPy vectorised
arr = np.arange(1, 5_000_001, dtype=object)     #numpy's int64 is different and specific as compare to python int, so we use dtype = object which is same as saying dtype = int to match python's int
t0 = time.time()
total_np = (arr ** 2).sum()
t_np = (time.time() - t0) * 1000

print(f"Python loop : {t_loop:.2f} ms  -->  result = {total_loop}")
print(f"NumPy       : {t_np:.2f} ms  -->  result = {total_np}")
print(f"Speedup     : {int(t_loop / t_np)}×")
print(f"Same answer : {total_loop == total_np}")

Python loop : 1160.16 ms  -->  result = 41666679166667500000
NumPy       : 501.94 ms  -->  result = 41666679166667500000
Speedup     : 2×
Same answer : True


### Q10 - linspace for scientific sampling (1 mark)

A pharmacokinetics study measures drug concentration every 0.5 hours  
over a 12-hour window.

1. Create a `time_points` array using `np.linspace()` for hours 0.0 through 12.0  
   at 0.5-hour intervals (25 points). Print it.

2. The drug follows a simple decay model:  
   `concentration = 100 * np.exp(-0.3 * time_points)`  
   Compute and print the concentration at every time point.

3. Find and print:
   - The time point where concentration first drops below 10.0 mg/L  
     (use boolean masking on `time_points`)
   - The maximum concentration and when it occurs
   - The average concentration over the full 12 hours

In [90]:
# 1. Time points
time_points = np.linspace(0.0, 12.0, 25)
print("Time points (hours):", time_points)

# 2. Decay model
concentration = 100 * np.exp(-0.3 * time_points)
print(f"\nConcentration (mg/L): {concentration.round(3)}")

# 3a. First time concentration drops below 10.0
below10 = time_points[concentration < 10.0]
print(f"\nFirst time below 10 mg/L: {below10[0]:.1f} hours")

# 3b. Max concentration
max_idx = np.argmax(concentration)      #argmax returns indices of max values or index of highest value, used in CNN to get the index of prediction with highest probability
print(f"Max concentration: {concentration[max_idx]:.2f} mg/L at {time_points[max_idx]:.1f} hours")

# 3c. Average
print(f"Average concentration over 12 hours: {concentration.mean():.3f} mg/L")

Time points (hours): [ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12. ]

Concentration (mg/L): [100.     86.071  74.082  63.763  54.881  47.237  40.657  34.994  30.119
  25.924  22.313  19.205  16.53   14.227  12.246  10.54    9.072   7.808
   6.721   5.784   4.979   4.285   3.688   3.175   2.732]

First time below 10 mg/L: 8.0 hours
Max concentration: 100.00 mg/L at 0.0 hours
Average concentration over 12 hours: 28.041 mg/L


## Part B - WHO Global Health Dataset
*10 questions · 1 mark each*

The dataset below represents a simplified version of WHO global health indicators
for 10 countries across 5 health metrics.

**Columns (5 metrics):**

0. Life expectancy at birth (years)
1. Under-5 mortality rate (per 1,000 live births)
2. Adult obesity rate (%)
3. Hospital beds per 10,000 population
4. Health expenditure per capita (USD)

**Rows (10 countries):**  
Pakistan, India, Bangladesh, Sri Lanka, Nepal, China, Iran, Turkey, Egypt, Nigeria

Run the dataset cell below before answering questions Q11–Q20.

In [91]:
# DATASET - run this cell before Q11-Q20
np.random.seed(42)

countries = np.array(['Pakistan','India','Bangladesh','Sri Lanka','Nepal',
                      'China','Iran','Turkey','Egypt','Nigeria'])

metrics   = np.array(['Life_Exp','U5_Mortality','Obesity_Pct',
                      'Hospital_Beds','Health_Expenditure'])

# Shape: (10 countries, 5 metrics)
health = np.array([
    # LifeExp  U5Mort  ObesePct  Beds   Expend
    [ 67.3,    65.0,   27.0,    6.0,   43.0],   # Pakistan
    [ 69.7,    33.0,   22.9,    5.0,   75.0],   # India
    [ 72.6,    28.0,   20.1,    8.0,   88.0],   # Bangladesh
    [ 76.4,    8.0,    22.1,   40.0,  395.0],   # Sri Lanka
    [ 70.5,    32.0,   21.0,    3.0,   71.0],   # Nepal
    [ 76.9,    8.0,    19.3,   42.0,  757.0],   # China
    [ 75.5,    14.0,   25.1,   15.0,  524.0],   # Iran
    [ 77.7,    9.0,    32.1,   28.0,  496.0],   # Turkey
    [ 70.2,    22.0,   33.0,   15.0,  226.0],   # Egypt
    [ 54.7,    117.0,  8.9,    5.0,   83.0],    # Nigeria
], dtype=np.float64)

print('Dataset shape:', health.shape)
print('\nColumn:', metrics)
print('\nFirst 3 rows:')
print(health[:3])

Dataset shape: (10, 5)

Column: ['Life_Exp' 'U5_Mortality' 'Obesity_Pct' 'Hospital_Beds'
 'Health_Expenditure']

First 3 rows:
[[67.3 65.  27.   6.  43. ]
 [69.7 33.  22.9  5.  75. ]
 [72.6 28.  20.1  8.  88. ]]


### Q11 - Descriptive statistics per metric (1 mark)

For each of the 5 health metrics, compute and print:
- Mean
- Median
- Standard deviation (round to 2 decimal places)
- Minimum and maximum value

Format the output as a table - one row per metric:
```
Metric              Mean    Median    Std     Min      Max
Life_Exp            71.15   70.10     5.74    54.70    77.70
...
```
*Hint: `axis=0` collapses across countries (rows), giving one value per metric.*

In [92]:
# Q11 - your answer here
metrics   = np.array(['Life_Exp','U5_Mortality','Obesity_Pct',
                      'Hospital_Beds','Health_Expenditure'])

means   = health.mean(axis=0)       #returns column wise mean values in a array
medians = np.median(health, axis=0)    #returns column wise meadian values in a array
stds    = health.std(axis=0)        #returns column wise standard deviation values in a array
mins    = health.min(axis=0)        #returns column wise minimum values in a array
maxs    = health.max(axis=0)

header = f"{'Metric':<22} {'Mean':>8} {'Median':>8} {'Std':>8} {'Min':>8} {'Max':>8}"
print(header)
print("-" * len(header))
for i, m in enumerate(metrics):
    print(f"{m:<22} {means[i]:>8.2f} {medians[i]:>8.2f} {stds[i]:>8.2f} {mins[i]:>8.2f} {maxs[i]:>8.2f}")

Metric                     Mean   Median      Std      Min      Max
-------------------------------------------------------------------
Life_Exp                  71.15    71.55     6.43    54.70    77.70
U5_Mortality              33.60    25.00    32.27     8.00   117.00
Obesity_Pct               23.15    22.50     6.55     8.90    33.00
Hospital_Beds             16.70    11.50    14.03     3.00    42.00
Health_Expenditure       275.80   157.00   238.17    43.00   757.00


### Q12 - Ranking countries by life expectancy (1 mark)

1. Extract the life expectancy column (column 0) as `life_exp`.
2. Use `np.argsort()` to rank countries from **highest to lowest** life expectancy.
3. Print the rankings as a numbered table:
   ```
   Rank 1: Turkey       - 77.7 years
   Rank 2: China        - 76.9 years
   ...
   ```
4. Print the range (max − min) and comment on whether the gap is large or small
   in the context of global health equity.

In [93]:
# Q12 - your answer here

life_exp = health[:, 0]     #all rows but first column only means life expectancy
rank_idx = np.argsort(life_exp)[::-1]   #argsort returns an array of indices (not values) from lowest to higest then we apply reverse indexing to get highest to lowest

print("Life Expectancy Ranking:")
print("-" * 35)
for rank, idx in enumerate(rank_idx):
    print(f"  Rank {rank+1}: {countries[idx]:<20}| {life_exp[idx]:.1f} years")

span = life_exp.max() - life_exp.min()
print(f"\nRange: {span:.1f} years")
# A 23-year gap between the highest (Turkey) and lowest (Nigeria) life expectancy
# reflects deep structural inequalities in healthcare access and socioeconomic conditions.

Life Expectancy Ranking:
-----------------------------------
  Rank 1: Turkey              | 77.7 years
  Rank 2: China               | 76.9 years
  Rank 3: Sri Lanka           | 76.4 years
  Rank 4: Iran                | 75.5 years
  Rank 5: Bangladesh          | 72.6 years
  Rank 6: Nepal               | 70.5 years
  Rank 7: Egypt               | 70.2 years
  Rank 8: India               | 69.7 years
  Rank 9: Pakistan            | 67.3 years
  Rank 10: Nigeria             | 54.7 years

Range: 23.0 years


### Q13 - Boolean filtering across conditions (1 mark)

Using **boolean masks only** (no loops):

1. Identify countries with `life expectancy` **above the dataset mean**.
   Print their names and values.

2. Identify countries where **both** of the following hold:
   - Under-5 mortality > 20 per 1,000
   - Health expenditure < 100 USD per capita  
   These are countries facing the highest combined burden. Print their names.

3. Count how many countries have obesity rate **below** the dataset mean.
   Print the count and the country names.

In [94]:
# Q13 - your answer here
mean_life = health[:, 0].mean()

print(f"Countries: {countries}\n")
# 1. Above-mean life expectancy
mask1 = health[:, 0] > mean_life
print(f"1. Life expectancy above mean (> {round(mean_life, 2)} years):")
for c, v in zip(countries[mask1], health[mask1, 0]):
    print(f"   {c:<20} {v:.1f}")

# 2. High mortality AND low expenditure
mask2 = (health[:, 1] > 20) & (health[:, 4] < 100)
print("\n2. High U5 mortality (>20) AND low health spend (<100 USD):")
print(f"    {countries[mask2]}")

# 3. Below-mean obesity
mean_ob = health[:, 2].mean()
mask3 = health[:, 2] < mean_ob
print(f"\n3. Obesity rate below mean ({mean_ob:.1f}%): {(mask3).sum()} countries")
print(f"    {countries[mask3]}")

Countries: ['Pakistan' 'India' 'Bangladesh' 'Sri Lanka' 'Nepal' 'China' 'Iran'
 'Turkey' 'Egypt' 'Nigeria']

1. Life expectancy above mean (> 71.15 years):
   Bangladesh           72.6
   Sri Lanka            76.4
   China                76.9
   Iran                 75.5
   Turkey               77.7

2. High U5 mortality (>20) AND low health spend (<100 USD):
    ['Pakistan' 'India' 'Bangladesh' 'Nepal' 'Nigeria']

3. Obesity rate below mean (23.1%): 6 countries
    ['India' 'Bangladesh' 'Sri Lanka' 'Nepal' 'China' 'Nigeria']


### Q14 - Column-wise normalisation with broadcasting (1 mark)

Normalise the entire `health` matrix (using Min-Max Scaler) so each column (metric) is scaled to [0, 1]:

$$\text{scaled}_{ij} = \frac{x_{ij} - \min_j}{\max_j - \min_j}$$

1. Compute `col_min` and `col_max` using `axis=0`. Print their shapes - both should be (5,).
2. Apply the formula in **one broadcasting expression** (no loops, no reshape).
3. Verify: `health_scaled.min(axis=0)` should be all zeros,  
   `health_scaled.max(axis=0)` should be all ones. Print these.
4. Print Pakistan's scaled profile (first row) and interpret what a value of 0.0 means.

In [95]:
# Q14 - your answer here

col_min = health.min(axis=0)
col_max = health.max(axis=0)

print(f"\n column min values: {col_min}, \ncolumn max values: {col_max}\n")

print("col_min shape:", col_min.shape)
print("col_max shape:", col_max.shape)

# 2. Broadcasting normalisation - one expression
health_scaled = (health - col_min) / (col_max - col_min)

# print(health_scaled)

# 3. Verification
print("\nColumn mins after scaling:", health_scaled.min(axis=0).round(10))
print("Column maxs after scaling:", health_scaled.max(axis=0).round(10))

# 4. Pakistan's profile
print("\nPakistan's scaled profile:")
for m, v in zip(metrics, health_scaled[0]):
    interp = "(worst in dataset)" if v == 0.0 else ""
    print(f"  {m:<22}: {v:.4f} {interp}")
# A value of 0.0 means Pakistan scores the lowest in the dataset on that metric.


 column min values: [54.7  8.   8.9  3.  43. ], 
column max values: [ 77.7 117.   33.   42.  757. ]

col_min shape: (5,)
col_max shape: (5,)

Column mins after scaling: [0. 0. 0. 0. 0.]
Column maxs after scaling: [1. 1. 1. 1. 1.]

Pakistan's scaled profile:
  Life_Exp              : 0.5478 
  U5_Mortality          : 0.5229 
  Obesity_Pct           : 0.7510 
  Hospital_Beds         : 0.0769 
  Health_Expenditure    : 0.0000 (worst in dataset)


In [96]:
# to Verify Pattern Preservation after Min-Max scaler
corr = np.corrcoef(health[:, 0], health_scaled[:, 0])[0, 1]
print("Correlation:", corr)  # The linear correlation between raw data and scaled data must be exactly 1.0:

Correlation: 1.0


### Q15 - Z-score standardisation per metric (1 mark)

Compute z-scores for the `health` matrix column-wise:

$$z_{ij} = \frac{x_{ij} - \mu_j}{\sigma_j}$$

1. Compute `col_mean` and `col_std` with `axis=0`. Print shapes (both should be `(5,)`).
2. Compute `health_z` using broadcasting.
3. Verify column means are ≈ 0 and column stds are ≈ 1.  
   Print both rounded to 10 decimal places - they will not be exactly 0 and 1 due to
   floating-point arithmetic. That is expected.
4. Nigeria has the most extreme z-scores. Print Nigeria's full z-score profile
   and identify which metric has the most extreme deviation and in which direction.

In [97]:
# Q15 - your answer here
col_mean = health.mean(axis=0)
col_std  = health.std(axis=0)
print("col_mean shape:", col_mean.shape)
print("col_std  shape:", col_std.shape)

# 2. Z-score - one broadcasting expression
health_z = (health - col_mean) / col_std

# 3. Verify
print("\nColumn means of health_z (≈ 0):", health_z.mean(axis=0).round(10))
print("Column stds  of health_z (≈ 1):", health_z.std(axis=0).round(10))

# 4. Nigeria's profile (last row, index 9)
print("\nNigeria's z-score profile:")
nigeria_z = health_z[9]
for m, z in zip(metrics, nigeria_z):
    direction = "FAR ABOVE average" if z > 2 else ("FAR BELOW average" if z < -2 else "near average")
    print(f"  {m:<22}: {z:+.3f}  {direction}")
most_extreme_idx = np.argmax(np.abs(nigeria_z))     #argmax sees large positive numbers and ignore large negative numbers so abs prevents this
print(f"\nMost extreme: {metrics[most_extreme_idx]} (z = {nigeria_z[most_extreme_idx]:+.3f})")

col_mean shape: (5,)
col_std  shape: (5,)

Column means of health_z (≈ 0): [-0.  0.  0.  0. -0.]
Column stds  of health_z (≈ 1): [1. 1. 1. 1. 1.]

Nigeria's z-score profile:
  Life_Exp              : -2.558  FAR BELOW average
  U5_Mortality          : +2.585  FAR ABOVE average
  Obesity_Pct           : -2.176  FAR BELOW average
  Hospital_Beds         : -0.834  near average
  Health_Expenditure    : -0.810  near average

Most extreme: U5_Mortality (z = +2.585)


### Q16 - Composite Health Index (1 mark)

Build a **Composite Health Index (CHI)** for each country using weighted metrics.

The weights reflect relative importance (must sum to 1.0):

| Metric | Weight |
|--------|--------|
| Life expectancy (scaled) | 0.30 |
| Under-5 mortality (inverted: 1 - scaled) | 0.25 |
| Obesity (inverted: 1 - scaled) | 0.10 |
| Hospital beds (scaled) | 0.15 |
| Health expenditure (scaled) | 0.20 |

1. Use the `health_scaled` matrix from Q14.
2. Invert the columns where **lower is better** (Under-5 mortality and Obesity):  
   `1.0 - health_scaled[:, col]`.
3. Define `weights = np.array([0.30, 0.25, 0.10, 0.15, 0.20])` and compute  
   `chi = (adjusted_health * weights).sum(axis=1)` - this uses broadcasting.
4. Print a ranked table from highest CHI (healthiest) to lowest. Round to 3 decimal places.

In [98]:
# Q16 - your answer here
# health_scaled from Q14 must be available

weights = np.array([0.30, 0.25, 0.10, 0.15, 0.20])
print("Weights sum to:", weights.sum())

# Invert columns where lower is better (U5 mortality=col1, Obesity=col2)
adjusted = health_scaled.copy()
adjusted[:, 1] = 1.0 - health_scaled[:, 1]   # U5 mortality - lower is better
adjusted[:, 2] = 1.0 - health_scaled[:, 2]   # Obesity      - lower is better

# Weighted CHI - broadcasting: (10,5) * (5,) then sum over axis=1
chi = (adjusted * weights).sum(axis=1)

# Ranked table
rank_idx = np.argsort(chi)[::-1]
print("\nComposite Health Index Ranking:")
print("-" * 40)
for rank, idx in enumerate(rank_idx):
    print(f"  Rank {rank+1}: {countries[idx]:<22} CHI = {chi[idx]:.3f}")

Weights sum to: 1.0

Composite Health Index Ranking:
----------------------------------------
  Rank 1: China                  CHI = 0.946
  Rank 2: Sri Lanka              CHI = 0.819
  Rank 3: Turkey                 CHI = 0.774
  Rank 4: Iran                   CHI = 0.721
  Rank 5: Bangladesh             CHI = 0.523
  Rank 6: Egypt                  CHI = 0.517
  Rank 7: Nepal                  CHI = 0.459
  Rank 8: India                  CHI = 0.447
  Rank 9: Pakistan               CHI = 0.320
  Rank 10: Nigeria                CHI = 0.119


### Q17 - Aggregation with axis (1 mark)

Answer all questions using **axis-based aggregation** - no Python loops.

1. `axis=0` (across countries): which metric has the **highest variation** (std)?  
   Print the metric name and its std.

2. `axis=1` (across metrics): which country has the **highest mean** across all its  
   raw metric values? (Interpret with caution - raw scales differ, but the exercise
   teaches axis=1.) Print the country name.

3. `keepdims=True`: compute the column means and subtract them from `health`
   in a single broadcasting line. Print the shape of the result - it must be (10, 5).  
   This is the 'mean-centring' step used before PCA in machine learning.

4. Use `np.argmax(axis=0)` to find which country has the best value for
   each metric. Print metric name --> country name for all 5 metrics.

In [99]:
# Q17 - your answer here

# 1. Highest variation metric (axis=0 = across countries)
metric_stds = health.std(axis=0)
top_metric_idx = np.argmax(metric_stds)
print(f"1. Highest variation metric: {metrics[top_metric_idx]},  (std={metric_stds[top_metric_idx]:.2f})")

# 2. Country with highest mean across raw metrics (axis=1 = across metrics)
country_means = health.mean(axis=1)
top_country_idx = np.argmax(country_means)
print(f"2. Highest raw mean: {countries[top_country_idx]} ({country_means[top_country_idx]:.1f})")
# Note: this is dominated by Health_Expenditure (large scale), not clinically meaningful alone.

# 3. Mean-centring with keepdims
centered = health - health.mean(axis=0, keepdims=True)
print("3. Mean-centred shape:", centered.shape)

# 4. Best-performing country per metric
best_idx = np.argmax(health, axis=0)   # high=good for LifeExp, Beds, Expenditure
# For U5 mortality and Obesity, lower is better - so use argmin
best_idx[1] = np.argmin(health[:, 1])  # U5 mortality
best_idx[2] = np.argmin(health[:, 2])  # Obesity
print("\n4. Best country per metric:")
for m, idx in zip(metrics, best_idx):
    print(f"   {m:<22}: {countries[idx]}")

1. Highest variation metric: Health_Expenditure,  (std=238.17)
2. Highest raw mean: China (180.6)
3. Mean-centred shape: (10, 5)

4. Best country per metric:
   Life_Exp              : Turkey
   U5_Mortality          : Sri Lanka
   Obesity_Pct           : Nigeria
   Hospital_Beds         : China
   Health_Expenditure    : China


### Q18 - Correlation analysis with NumPy (1 mark)

We want to know: does higher health spending correlate with better life expectancy?

1. Extract `life_exp` (column 0) and `expenditure` (column 4) as 1D arrays.

2. Compute Pearson correlation **manually** using NumPy (no scipy):
   $$r = \frac{\sum (x_i - \bar{x})(y_i - \bar{y})}{\sqrt{\sum(x_i-\bar{x})^2 \cdot \sum(y_i-\bar{y})^2}}$$

3. Verify using `np.corrcoef(life_exp, expenditure)[0, 1]` - both must match.

4. Print the Pearson r rounded to 3 decimal places and write a one-line interpretation
   in a comment: is the relationship positive or negative, strong or weak?

In [101]:
# Q18 - your answer here
life_exp   = health[:, 0]
expenditure = health[:, 4]

# 2. Manual Pearson r
x_dev = life_exp   - life_exp.mean()
y_dev = expenditure - expenditure.mean()
r_manual = (x_dev * y_dev).sum() / np.sqrt((x_dev**2).sum() * (y_dev**2).sum())
print(f"Manual Pearson r    : {r_manual:.3f}")

# 3. Verify with np.corrcoef
r_np = np.corrcoef(life_exp, expenditure)[0, 1]
print(f"np.corrcoef result  : {r_np:.3f}")
print(f"Values match        : {abs(r_manual - r_np) < 1e-10}")

# 4. Interpretation
# r approx +0.6: strong positive correlation 
# countries that spend more per capita on health tend to have higher life expectancy.
print(f"\nInterpretation: r = {r_manual:.3f} --> mildly strong positive relationship.")
print("Countries with higher health expenditure tend to have longer life expectancy.")

Manual Pearson r    : 0.665
np.corrcoef result  : 0.665
Values match        : True

Interpretation: r = 0.665 --> mildly strong positive relationship.
Countries with higher health expenditure tend to have longer life expectancy.


### Q19 - Detecting and replacing outliers (1 mark)

The under-5 mortality column (column 1) has one country (Nigeria) with a very
high value that skews analysis.

1. Compute the mean and standard deviation of column 1.
2. Define an outlier as any value more than **2 standard deviations** above the mean.
3. Use a boolean mask to identify and print the outlier country and its value.
4. Create `u5_capped`, a copy of column 1 where the outlier is replaced
   by `mean + 2 * std` (Winsorisation - cap instead of delete).
5. Print the mean and std **before and after** capping. Comment on the change.

In [ ]:
# Q19 - your answer here
u5 = health[:, 1].copy()

print(f"u5: {u5}")
print(f"\ncountries: {countries}")

mean_u5 = u5.mean()
std_u5  = u5.std()
print(f"\nMean: {mean_u5:.2f}  Std: {std_u5:.2f}")

# 2. Outlier: >2 std above mean
threshold = mean_u5 + 2 * std_u5
mask_out  = u5 > threshold
print(f"\nOutlier threshold (mean + 2std): {threshold:.2f}")
print("Outlier countries:", countries[mask_out])
print("Outlier values   :", u5[mask_out])

# 4. Winsorise
u5_capped = u5.copy()
u5_capped[mask_out] = threshold

# 5. Before / after
print(f"\nBefore capping - mean: {u5.mean():.2f}  std: {u5.std():.2f}")
print(f"After  capping - mean: {u5_capped.mean():.2f}  std: {u5_capped.std():.2f}")
# Capping Nigeria's extreme value (117) pulls the mean down by ~2 points
# and reduces the std substantially, revealing the typical range more accurately. Search and see why the threshold with mean is not a good measure for outlier removal.

u5: [ 65.  33.  28.   8.  32.   8.  14.   9.  22. 117.]

countries: ['Pakistan' 'India' 'Bangladesh' 'Sri Lanka' 'Nepal' 'China' 'Iran'
 'Turkey' 'Egypt' 'Nigeria']

Mean: 33.60  Std: 32.27

Outlier threshold (mean + 2std): 98.13
Outlier countries: ['Nigeria']
Outlier values   : [117.]

Before capping - mean: 33.60  std: 32.27
After  capping - mean: 31.71  std: 27.54


### Q20 - Full pipeline: group comparison (1 mark)

Categorise the 10 countries into two groups based on **health expenditure**:
- `high_spend`: expenditure ≥ 200 USD per capita
- `low_spend`: expenditure < 200 USD per capita

For **each group** and **each of the 5 metrics**, compute the group mean.
Present the results as a comparison table:

```
Metric              High-Spend Mean   Low-Spend Mean   Difference
Life_Exp            ...               ...              ...
U5_Mortality        ...               ...              ...
...
```

Write two sentences in comments interpreting the most striking difference you observe.

In [111]:
# Q20 - your answer here
expend = health[:, 4]
mask_high = expend >= 200
mask_low  = expend <  200

high_mean = health[mask_high].mean(axis=0)
low_mean  = health[mask_low].mean(axis=0)
diff      = high_mean - low_mean

print(f"{'Metric':<22} {'High-Spend Mean':>18} {'Low-Spend Mean':>16} {'Difference':>12}")
print("-" * 72)
for m, h, l, d in zip(metrics, high_mean, low_mean, diff):
    print(f"{m:<22} {h:>18.2f} {l:>16.2f} {d:>+12.2f}")

print(f"\nHigh-spend countries: {countries[mask_high]}")
print(f"Low-spend countries : {countries[mask_low]}")
# High-spending countries enjoy ~8 more years of life expectancy on average.
# Under-5 mortality is dramatically lower in high-spending countries (~12.20 vs ~55.00),
# suggesting health investment has the strongest impact on child survival.

Metric                    High-Spend Mean   Low-Spend Mean   Difference
------------------------------------------------------------------------
Life_Exp                            75.34            66.96        +8.38
U5_Mortality                        12.20            55.00       -42.80
Obesity_Pct                         26.32            19.98        +6.34
Hospital_Beds                       28.00             5.40       +22.60
Health_Expenditure                 479.60            72.00      +407.60

High-spend countries: ['Sri Lanka' 'China' 'Iran' 'Turkey' 'Egypt']
Low-spend countries : ['Pakistan' 'India' 'Bangladesh' 'Nepal' 'Nigeria']


## Part C - Operations, Broadcasting & Linear Algebra
*10 questions · 1 mark each*

This part tests the material from Class 8: ufuncs, axis-based aggregation,
broadcasting rules, matrix operations, and reshaping.

### Q21 - Element-wise operations and ufuncs (1 mark)

```python
before = np.array([85.0, 90.0, 78.0, 110.0, 95.0])  # fasting glucose (mg/dL)
after  = np.array([82.0, 87.0, 81.0,  98.0, 91.0])  # glucose after medication
```

Using element-wise operations and ufuncs only (no loops):
1. `delta` = change after medication (after − before). Print.
2. `pct_change` = percentage change. Print rounded to 2 decimal places.
3. Apply `np.abs()` to delta. Print the absolute changes.
4. Use `np.clip()` to cap glucose values in `after` to the range [70, 100]. Print.
5. Simulate log-transform: `np.log(before)` and `np.log(after)`. Print both.

In [114]:
# Q21 - your answer here
before = np.array([85.0, 90.0, 78.0, 110.0, 95.0])
after  = np.array([82.0, 87.0, 81.0,  98.0, 91.0])

delta      = after - before
pct_change = (delta / before) * 100
abs_delta  = np.abs(delta)
clipped    = np.clip(after, 70, 100)
log_before = np.log(before)
log_after  = np.log(after)

print("1. Delta (after - before)     :", delta)
print("2. Percentage change (rounded)         :", pct_change.round(2))
print("3. Absolute changes           :", abs_delta)
print("4. Clipped after [70,100]     :", clipped)
print("5. log(before)                :", log_before.round(4))
print("   log(after)                 :", log_after.round(4))

1. Delta (after - before)     : [ -3.  -3.   3. -12.  -4.]
2. Percentage change (rounded)         : [ -3.53  -3.33   3.85 -10.91  -4.21]
3. Absolute changes           : [ 3.  3.  3. 12.  4.]
4. Clipped after [70,100]     : [82. 87. 81. 98. 91.]
5. log(before)                : [4.4427 4.4998 4.3567 4.7005 4.5539]
   log(after)                 : [4.4067 4.4659 4.3944 4.585  4.5109]


### Q22 - Aggregation with axis (1 mark)

A 4-patient, 7-day glucose monitoring matrix:
```python
glucose = np.array([
    [5.2, 5.8, 6.1, 5.5, 7.2, 6.8, 5.9],
    [8.5, 9.1, 8.8, 7.9, 9.5, 8.3, 8.7],
    [4.8, 5.0, 4.9, 5.3, 4.7, 5.1, 4.6],
    [6.9, 7.3, 7.1, 8.2, 6.8, 7.5, 7.0],
])
```

Using axis-based aggregation:
1. Mean glucose per patient (axis=1). Which patient has the highest average?
2. Mean glucose per day (axis=0). Which day had the highest average across all patients?
3. Overall max, min, and std (no axis - collapse to scalar).
4. Cumulative glucose per patient over the 7 days: `np.cumsum(axis=1)`. Print.
5. Using `keepdims=True`, subtract each patient's daily mean so readings are centred.

In [116]:
# Q22 - your answer here
glucose = np.array([
    [5.2, 5.8, 6.1, 5.5, 7.2, 6.8, 5.9],
    [8.5, 9.1, 8.8, 7.9, 9.5, 8.3, 8.7],
    [4.8, 5.0, 4.9, 5.3, 4.7, 5.1, 4.6],
    [6.9, 7.3, 7.1, 8.2, 6.8, 7.5, 7.0],
])


# 1. Per-patient mean (axis=1)
patient_means = glucose.mean(axis=1)
print("1. Mean per patient:", patient_means.round(3))
print("   Highest average: Patient", np.argmax(patient_means) + 1,
      f"({patient_means.max():.3f} mmol/L)")

# 2. Per-day mean (axis=0)
day_means = glucose.mean(axis=0)
print("\n2. Mean per day:", day_means.round(3))
print("   Highest day: Day", np.argmax(day_means) + 1,
      f"({day_means.max():.3f} mmol/L)")

# 3. Overall
print(f"\n3. Overall max={glucose.max():.1f}  min={glucose.min():.1f}  std={glucose.std():.3f}")

# 4. Cumulative sum per patient
print("\n4. Cumulative glucose per patient:\n", glucose.cumsum(axis=1).round(2))

# 5. Mean-centring per patient using keepdims
centred = glucose - glucose.mean(axis=1, keepdims=True)
print("\n5. Mean-centred shape:", centred.shape)
print("   Patient means after centring:", centred.mean(axis=1).round(10))

1. Mean per patient: [6.071 8.686 4.914 7.257]
   Highest average: Patient 2 (8.686 mmol/L)

2. Mean per day: [6.35  6.8   6.725 6.725 7.05  6.925 6.55 ]
   Highest day: Day 5 (7.050 mmol/L)

3. Overall max=9.5  min=4.6  std=1.478

4. Cumulative glucose per patient:
 [[ 5.2 11.  17.1 22.6 29.8 36.6 42.5]
 [ 8.5 17.6 26.4 34.3 43.8 52.1 60.8]
 [ 4.8  9.8 14.7 20.  24.7 29.8 34.4]
 [ 6.9 14.2 21.3 29.5 36.3 43.8 50.8]]

5. Mean-centred shape: (4, 7)
   Patient means after centring: [ 0. -0.  0. -0.]


### Q23 - Broadcasting: shapes and rules (1 mark)

`Predict the` **`output shape`** **before running** each expression, then verify.

```python
A = np.ones((4, 3))
B = np.ones((3,))
C = np.ones((4, 1))
D = np.ones((1, 3))
E = np.ones((4, 3, 2))
F = np.ones((3, 2))
```

For each expression:
1. `A + B`
2. `A + C`
3. `C + D`
4. `E + F`
5. `A + np.ones((5,))` - this one raises an error. Print the error message  
   using `try/except` and explain **in a comment** which broadcasting rule is violated.

In [119]:
# Q23 - your answer here
A = np.ones((4, 3))
B = np.ones((3,))
C = np.ones((4, 1))
D = np.ones((1, 3))
E = np.ones((4, 3, 2))
F = np.ones((3, 2))


print(f"1. A+B shape: {(A + B).shape}   predicted: (4,3)")
print(f"2. A+C shape: {(A + C).shape}   predicted: (4,3)")
print(f"3. C+D shape: {(C + D).shape}   predicted: (4,3)")
print(f"4. E+F shape: {(E + F).shape}   predicted: (4,3,2)")

# 5. A + ones((5,)) — should fail
try:
    result = A + np.ones((5,))
except ValueError as e:
    print(f"\n5. ValueError: {e}")
    # Rule violated: trailing dimensions must be equal or one of them must be 1.
    # A (4,3) has trailing dim 3; ones((5,)) has trailing dim 5 after rule 1st is applied (1,5).
    # 3 ≠ 5 and neither is 1 --> broadcasting is impossible until or unless we do manual broadcasting somehow.

1. A+B shape: (4, 3)   predicted: (4,3)
2. A+C shape: (4, 3)   predicted: (4,3)
3. C+D shape: (4, 3)   predicted: (4,3)
4. E+F shape: (4, 3, 2)   predicted: (4,3,2)

5. ValueError: operands could not be broadcast together with shapes (4,3) (5,) 


### Q24 - Broadcasting for data centering (1 mark)

```python
patients = np.array([
    [68.0, 1.72, 7.2, 128.0],  # weight(kg), height(m), glucose, bp_sys
    [82.0, 1.68, 8.5, 142.0],
    [55.0, 1.60, 5.1, 115.0],
    [91.0, 1.80, 9.3, 155.0],
    [73.0, 1.65, 6.8, 135.0],
    [78.0, 1.74, 7.5, 140.0],
])
```

1. Compute `pop_mean` and `pop_std` across patients (axis=0). Print shapes.
2. Z-score normalise using one broadcasting expression. Print result shape - must be (6, 4).
3. Add a BMI column: `bmi = weight / height**2`. Use array slicing and broadcasting
   to compute it for all 6 patients in one expression. Print the BMI values.
4. Concatenate the BMI column onto the normalised matrix: result shape must be (6, 5).

In [120]:
# Q24 - your answer here
patients = np.array([
    [68.0, 1.72, 7.2, 128.0],
    [82.0, 1.68, 8.5, 142.0],
    [55.0, 1.60, 5.1, 115.0],
    [91.0, 1.80, 9.3, 155.0],
    [73.0, 1.65, 6.8, 135.0],
    [78.0, 1.74, 7.5, 140.0],
])


# 1. Population mean and std
pop_mean = patients.mean(axis=0)
pop_std  = patients.std(axis=0)
print(f"pop_mean shape: {pop_mean.shape}")
print(f"pop_std  shape: {pop_std.shape}")

# 2. Z-score normalise
patients_z = (patients - pop_mean) / pop_std
print(f"\nNormalised shape: {patients_z.shape}")
print(patients_z.round(3))

# 3. BMI = weight / height^2 using column slicing
weight = patients[:, 0]
height = patients[:, 1]
bmi    = weight / (height ** 2)
print(f"\nBMI values: {bmi.round(2)}")

# 4. Concatenate BMI as new column
bmi_col = bmi[:, np.newaxis]                          # (6,1)
patients_z_bmi = np.concatenate([patients_z, bmi_col], axis=1)
print(f"Shape with BMI column: {patients_z_bmi.shape}")

pop_mean shape: (4,)
pop_std  shape: (4,)

Normalised shape: (6, 4)
[[-0.575  0.336 -0.151 -0.633]
 [ 0.664 -0.285  0.831  0.498]
 [-1.726 -1.527 -1.737 -1.684]
 [ 1.461  1.579  1.435  1.549]
 [-0.133 -0.751 -0.453 -0.067]
 [ 0.31   0.647  0.076  0.337]]

BMI values: [22.99 29.05 21.48 28.09 26.81 25.76]
Shape with BMI column: (6, 5)


### Q25 - Matrix multiplication: the neural network forward pass (1 mark)

You are simulating **one linear layer** of a neural network.

```python
np.random.seed(7)
X = np.random.randn(5, 4)         # 5 samples, 4 input features
W = np.random.randn(4, 6)         # weight matrix: 4 inputs -> 6 neurons
b = np.random.randn(6)            # bias vector: one per neuron
```

1. Compute `Z = X @ W + b`. Print `Z` and its shape (should be 5×6).
2. Confirm that `Z[0]` equals `np.dot(X[0], W) + b`. Print `True` or `False`.
3. Apply the ReLU activation: `A = np.maximum(0, Z)`. Print how many elements  
   were 'zeroed out' (were negative in Z but become 0 in A).
4. Add a second layer: `W2 = np.random.randn(6, 3)`, `b2 = np.random.randn(3)`.  
   Compute `Z2 = A @ W2 + b2`. Print its shape (should be 5×3).
5. Explain in a comment: why must the INNER dimensions match for `@`?  
   Use the shapes in this problem as your example.

In [ ]:
# Q25 - your answer here
np.random.seed(7)
X = np.random.randn(5, 4)
W = np.random.randn(4, 6)
b = np.random.randn(6)

# 1. First layer linear combination
Z = X @ W + b
print("1. Z shape:", Z.shape)
print("   Z:\n", Z.round(4))

# 2. Verify Z[0] = dot(X[0], W) + b
print("\n2. Z[0] matches np.dot(X[0],W)+b:", np.allclose(Z[0], np.dot(X[0], W) + b))

# 3. ReLU
A = np.maximum(0, Z)
zeroed_out = (Z < 0).sum()
print(f"\n3. Elements zeroed by ReLU: {zeroed_out} out of {Z.size}")

# # 4. Second layer
# # Output size can be anything you choose (e.g., 2 output neurons)
# W2 = np.random.randn(6, 2)  # Must have 6 rows to match A's 6 columns
# b2 = np.random.randn(2)     # Must match W2's 2 output columns

# Z2 = A @ W2 + b2
# print("\n4. Z2 shape:", Z2.shape)
# print("   Z2:\n", Z2.round(4))

# 5. Why inner dimensions must match:
# X @ W requires X.shape[1] == W.shape[0]  -->  4 == 4 ✓
# A @ W2 requires A.shape[1] == W2.shape[0] -->  6 == 6 ✓
# The inner dimension is the 'contraction axis' - each output neuron
# is a dot product of an input vector with one column of the weight matrix.

1. Z shape: (5, 6)
   Z:
 [[ 1.9366 -0.5926 -0.4854  5.7768  0.7306 -3.7355]
 [-6.1091 -1.352  -0.7827  0.9624 -0.692   1.9418]
 [ 0.4578 -3.2985  1.7662  4.5074  0.433  -2.1421]
 [-2.9342 -0.7783 -0.8074  3.804  -0.0927 -0.7988]
 [-3.9923 -1.3512 -1.5516  3.4143 -1.0454  0.3542]]

2. Z[0] matches np.dot(X[0],W)+b: True

3. Elements zeroed by ReLU: 18 out of 30

4. Z2 shape: (5, 2)
   Z2:
 [[-4.7555  5.9286]
 [-2.1967 -1.5195]
 [-5.9671  4.0392]
 [-5.5583  3.6077]
 [-5.1297  2.737 ]]


### Q26 - Norms and distances (1 mark)

```python
patient_a = np.array([5.2, 128.0, 22.1, 68.0])  # glucose, bp, bmi, weight
patient_b = np.array([8.5, 145.0, 29.3, 84.0])
patient_c = np.array([4.9, 112.0, 20.8, 61.0])
```

1. Compute the **L2 (Euclidean) distance** between patient_a and patient_b  
   `manually`: `np.sqrt(np.sum((a-b)**2))`. Print.
2. Verify with `np.linalg.norm(patient_a - patient_b)`. Print `True` if they match.
3. Find who is clinically **closer** to patient_a: patient_b or patient_c?  
   Print the two distances and the answer.
4. Compute the **cosine similarity** between patient_a and patient_b:  
   $\cos(\theta) = \frac{a \cdot b}{\|a\| \|b\|}$.  
   Print the result rounded to 4 decimal places.
5. Comment: why might Euclidean distance be misleading here without normalisation?

In [126]:
# Q26 - your answer here
patient_a = np.array([5.2, 128.0, 22.1, 68.0])
patient_b = np.array([8.5, 145.0, 29.3, 84.0])
patient_c = np.array([4.9, 112.0, 20.8, 61.0])


# 1. Manual L2 distance a–b
dist_ab_manual = np.sqrt(np.sum((patient_a - patient_b)**2))
print(f"1. Manual L2(a,b): {dist_ab_manual:.4f}")

# 2. Verify with linalg.norm
dist_ab_linalg = np.linalg.norm(patient_a - patient_b)
print(f"2. linalg.norm match: {np.isclose(dist_ab_manual, dist_ab_linalg)}")

# 3. Who is closer to a?
dist_ac = np.linalg.norm(patient_a - patient_c)
print(f"\n3. dist(a,b) = {dist_ab_manual:.4f}")
print(f"   dist(a,c) = {dist_ac:.4f}")
closer = "Patient B" if dist_ab_manual < dist_ac else "Patient C"
print(f"   Closer to Patient A: {closer}")

# 4. Cosine similarity a–b
cos_sim = np.dot(patient_a, patient_b) / (np.linalg.norm(patient_a) * np.linalg.norm(patient_b))
print(f"\n4. Cosine similarity(a,b): {cos_sim:.4f}, though both a and b are distance apart still they point in the same direction,\n it is just that b is much longer in magnitude (L2 norm)")

# 5. Without normalisation, bp_sys (≈128) dominates distance calculations
# because its numeric scale is ~25× larger than glucose (≈5).
# Always z-score or min-max scale before computing distances.

1. Manual L2(a,b): 24.6522
2. linalg.norm match: True

3. dist(a,b) = 24.6522
   dist(a,c) = 17.5151
   Closer to Patient A: Patient C

4. Cosine similarity(a,b): 0.9990, though both a and b are distance apart still they point in the same direction,
 it is just that b is much longer in magnitude (L2 norm)


### Q27 - Element-wise vs matrix multiply (1 mark)

A very common mistake in NumPy is confusing `*` (element-wise) with `@` (matrix multiply).

```python
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
```

1. Compute `A * B` and `A @ B`. Print both and their shapes.
2. Are they the same? Print `True` or `False`.
3. Compute the **transpose** of A: `A.T`. Print it and its shape.
4. Compute `A.T @ A` (the Gram matrix). Print it.
5. Verify: `A.T @ A` is **symmetric** (equals its own transpose).  
   Print `np.array_equal(A.T @ A, (A.T @ A).T)`.

In [127]:
# Q27 - your answer here
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])


ew  = A * B        # element-wise
mm  = A @ B        # matrix multiply

print("1. A * B (element-wise):\n", ew)
print("   A @ B (matrix multiply):\n", mm)
print("\n2. Are they the same?", np.array_equal(ew, mm))

print("\n3. A.T:\n", A.T, "  shape:", A.T.shape)

gram = A.T @ A
print("\n4. Gram matrix A.T @ A:\n", gram)

print("\n5. Gram matrix is symmetric:", np.array_equal(gram, gram.T))

1. A * B (element-wise):
 [[ 5 12]
 [21 32]]
   A @ B (matrix multiply):
 [[19 22]
 [43 50]]

2. Are they the same? False

3. A.T:
 [[1 3]
 [2 4]]   shape: (2, 2)

4. Gram matrix A.T @ A:
 [[10 14]
 [14 20]]

5. Gram matrix is symmetric: True


### Q28 - Fancy reshaping pipeline (1 mark)

You receive a flat 1D sensor stream and must reshape it into a usable matrix.

```python
sensor_stream = np.arange(1, 121)   # 120 readings
```

1. Reshape into `(24, 5)`: 24 hours × 5 sensors. Print shape.
2. From the (24, 5) matrix, extract **hours 8 through 16** (working hours) for
   **sensors 1, 2, and 4 only** (zero-indexed). Print the result and its shape.
3. Flatten that result back to 1D using `.ravel()`. Print and confirm shape is (27,).
4. Compare `.ravel()` vs `.flatten()`: modify the ravel output and check  
   whether the original (24, 5) matrix changed. Print `True` if it changed.
5. What does this tell you about `.ravel()` vs `.flatten()`?  
   Write your answer in a comment.

In [ ]:
# Q28 - your answer here
sensor_stream = np.arange(1, 121)

# 1. Reshape to (24, 5)
matrix_24x5 = sensor_stream.reshape(24, 5)
print("1. Reshaped shape:", matrix_24x5.shape)

# 2. Hours 8–16 (indices 8:17), sensors 1, 2, 4 (indices [1,2,4])
working_hours = matrix_24x5[8:17, :][:, [1, 2, 4]]
print("\n2. Working-hours extract:\n", working_hours, "\n   shape:", working_hours.shape)

# 3. Flatten with ravel
flat_ravel = working_hours.ravel()
print("\n3. Ravelled shape:", flat_ravel.shape)

# 4. Does modifying ravel output change the original?
flat_test = working_hours.ravel()
flat_test[0] = 9999
print("\n4. Original changed after ravel modification:", working_hours[0, 0] == 9999)

# 5. ravel() returns a VIEW when possible (shares memory with working_hours),
# so modifying it CAN change the original.
# flatten() ALWAYS returns an independent copy - safer if you need isolation.

1. Reshaped shape: (24, 5)

2. Working-hours extract:
 [[42 43 45]
 [47 48 50]
 [52 53 55]
 [57 58 60]
 [62 63 65]
 [67 68 70]
 [72 73 75]
 [77 78 80]
 [82 83 85]] 
   shape: (9, 3)

3. Ravelled shape: (27,)

4. Original changed after ravel modification: False


### Q29 - Outer product and pairwise computation (1 mark)

```python
concentrations = np.array([0.1, 0.5, 1.0, 2.0, 5.0])  # drug concentrations (mg/L)
response_curve = np.array([1.2, 0.9, 0.7, 0.5, 0.2])  # measured inhibition (0–1)
```

1. Compute the **outer product** `np.outer(concentrations, response_curve)`.
   Print its shape - should be (5, 5). Explain what each cell [i,j] represents.
2. Create a (5, 1) column vector and (1, 5) row vector from `concentrations`  
   using `[:, np.newaxis]` and `[np.newaxis, :]`. Print both shapes.
3. Compute the **pairwise absolute differences** between all concentration values:  
   `diff_matrix = np.abs(concentrations[:, None] - concentrations[None, :])`.  
   Print the matrix.
4. The diagonal of `diff_matrix` should be all zeros. Verify with `np.diag()`.

In [129]:
# Q29 - your answer here
concentrations = np.array([0.1, 0.5, 1.0, 2.0, 5.0])
response_curve = np.array([1.2, 0.9, 0.7, 0.5, 0.2])


# 1. Outer product
outer = np.outer(concentrations, response_curve)
print("1. Outer product shape:", outer.shape)
print(outer.round(3))
# Cell [i,j] = concentrations[i] × response_curve[j]:
# the product of the i-th concentration with the j-th inhibition response.

# 2. Column and row vectors
col_vec = concentrations[:, np.newaxis]
row_vec = concentrations[np.newaxis, :]
print("\n2. col_vec shape:", col_vec.shape)
print("   row_vec shape:", row_vec.shape)

# 3. Pairwise absolute differences
diff_matrix = np.abs(concentrations[:, None] - concentrations[None, :])
print("\n3. Pairwise differences:\n", diff_matrix.round(3))

# 4. Diagonal should be all zeros
print("\n4. Diagonal:", np.diag(diff_matrix))
print("   All zero:", np.all(np.diag(diff_matrix) == 0))

1. Outer product shape: (5, 5)
[[0.12 0.09 0.07 0.05 0.02]
 [0.6  0.45 0.35 0.25 0.1 ]
 [1.2  0.9  0.7  0.5  0.2 ]
 [2.4  1.8  1.4  1.   0.4 ]
 [6.   4.5  3.5  2.5  1.  ]]

2. col_vec shape: (5, 1)
   row_vec shape: (1, 5)

3. Pairwise differences:
 [[0.  0.4 0.9 1.9 4.9]
 [0.4 0.  0.5 1.5 4.5]
 [0.9 0.5 0.  1.  4. ]
 [1.9 1.5 1.  0.  3. ]
 [4.9 4.5 4.  3.  0. ]]

4. Diagonal: [0. 0. 0. 0. 0.]
   All zero: True


### Q30 - One-hot encoding with broadcasting (1 mark)

One-hot encoding is fundamental in machine learning for converting categorical labels
into a matrix representation that models can process.

```python
labels = np.array([0, 2, 1, 0, 2, 1, 0, 1, 2, 0])  # class labels: 0=Normal, 1=Pre-diabetic, 2=Diabetic
n_classes = 3
```

1. Use broadcasting to create the one-hot matrix in **one line** (no loops):
   `(labels[:, None] == np.arange(n_classes)[None, :]).astype(int)`  
   Print the result and its shape (should be 10×3).
2. Verify: every row sums to exactly 1. Print `np.all(one_hot.sum(axis=1) == 1)`.
3. Count the samples in each class using `one_hot.sum(axis=0)`. Print.
4. Recover the original labels from the one-hot matrix using `np.argmax(axis=1)`.
   Verify `np.array_equal(recovered, labels)` prints `True`.
5. Comment: why is one-hot preferred over using raw integer labels (0, 1, 2)  
   in neural network output layers?

In [130]:
# Q30 - your answer here
labels    = np.array([0, 2, 1, 0, 2, 1, 0, 1, 2, 0])
n_classes = 3


# 1. One-hot encoding via broadcasting — one line
one_hot = (labels[:, None] == np.arange(n_classes)[None, :]).astype(int)
print("1. One-hot matrix:\n", one_hot)
print("   Shape:", one_hot.shape)

# 2. Each row sums to 1
print("\n2. All row sums == 1:", np.all(one_hot.sum(axis=1) == 1))

# 3. Class counts
print("\n3. Samples per class:", one_hot.sum(axis=0))

# 4. Recover original labels
recovered = np.argmax(one_hot, axis=1)
print("\n4. Recovered == original:", np.array_equal(recovered, labels))

# 5. Raw integer labels (0,1,2) imply an ordinal relationship (2 > 1 > 0)
# that doesn't exist in categorical classes like Normal/Pre-diabetic/Diabetic.
# One-hot treats all classes as equidistant, which is mathematically correct
# for softmax cross-entropy output layers in neural networks.

1. One-hot matrix:
 [[1 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]]
   Shape: (10, 3)

2. All row sums == 1: True

3. Samples per class: [4 3 3]

4. Recovered == original: True


## Part D - Pakistan Crop Yield Dataset
*10 questions · 1 mark each*

This dataset captures annual crop production data across **8 provinces/regions**
of Pakistan for **4 major crops** over **5 years (2019–2023)**.

**Shape: (8 regions, 4 crops, 5 years)** - a 3D array.

**Rows (8 regions):** Punjab, Sindh, KPK, Balochistan, Gilgit-Baltistan, AJK, FATA, ICT  
**Slices/depth (4 crops):** Wheat, Rice, Cotton, Sugarcane  
**Pages (5 years):** 2019, 2020, 2021, 2022, 2023

Yields are in **thousand tonnes**.

Run the dataset cell below before answering Q31–Q40.

In [131]:
# DATASET - run this cell before Q31-Q40
np.random.seed(99)

regions = np.array(['Punjab','Sindh','KPK','Balochistan',
                    'Gilgit-Baltistan','AJK','FATA','ICT'])
crops   = np.array(['Wheat','Rice','Cotton','Sugarcane'])
years   = np.array([2019, 2020, 2021, 2022, 2023])

# Base yields (thousand tonnes) - reflects real relative magnitudes
base = np.array([
    # Wheat  Rice  Cotton  Sugarcane
    [21500,  3800,  9200,  68000],   # Punjab
    [ 4200,  2900,  3100,  19000],   # Sindh
    [  950,   120,    10,    420],   # KPK
    [ 1100,   200,   850,   1200],   # Balochistan
    [   80,    15,     0,     30],   # Gilgit-Baltistan
    [   45,    20,     0,     60],   # AJK
    [   30,    12,     2,     40],   # FATA
    [    5,     2,     1,     10],   # ICT
], dtype=np.float64)

# Build 3D array: (8, 4, 5) = (regions, crops, years)
# Add realistic year-to-year variation (±8% random fluctuation)
variation = 1.0 + np.random.uniform(-0.08, 0.08, (8, 4, 5))
yields = base[:, :, np.newaxis] * variation  # broadcasting: (8,4,1) * (8,4,5) -> (8,4,5)

# Simulate a drought year: 2022 (index 3) reduced wheat by 15% in Balochistan
yields[3, 0, 3] *= 0.85
# Flood year: 2022 Sindh rice down 20%
yields[1, 1, 3] *= 0.80

print('Dataset shape (regions, crops, years):', yields.shape)
print('\nRegions:', regions)
print('Crops:  ', crops)
print('Years:  ', years)
print('\nPunjab Wheat yields (2019-2023):', yields[0, 0, :].round(0))

Dataset shape (regions, crops, years): (8, 4, 5)

Regions: ['Punjab' 'Sindh' 'KPK' 'Balochistan' 'Gilgit-Baltistan' 'AJK' 'FATA'
 'ICT']
Crops:   ['Wheat' 'Rice' 'Cotton' 'Sugarcane']
Years:   [2019 2020 2021 2022 2023]

Punjab Wheat yields (2019-2023): [22093. 21459. 22620. 19888. 22560.]


### Q31 - Exploring a 3D array (1 mark)

Understanding the shape before analysis prevents every indexing error.

1. Print the shape, ndim, size, and dtype of `yields`.
2. Extract and print **Punjab's** complete data: all 4 crops, all 5 years.  
   Shape should be (4, 5).
3. Extract **all regions' Wheat yield for 2023** (last year).  
   Shape should be (8,). Print with region names alongside.
4. Extract **Cotton yields for all regions, all years** - shape (8, 5). Print.
5. Extract the yield for `KPK`, `Rice`, `2021` as a single scalar.
   Print it with appropriate label.

In [134]:
# Q31 - your answer here
# 1. Array metadata
print(f"1. shape: {yields.shape}, ndim: {yields.ndim}, size: {yields.size}, dtype: {yields.dtype}")

# 2. Punjab (index 0) — all crops, all years
punjab_data = yields[0]
print(f"\n2. Punjab data shape: {punjab_data.shape}")
print(punjab_data.round(0))

# 3. All regions, Wheat (crop 0), 2023 (year index 4)
wheat_2023 = yields[:, 0, 4]
print("\n3. Wheat yields 2023 (all regions):")
for r, v in zip(regions, wheat_2023):
    print(f"   {r:<22}: {v:,.0f} kt")

# 4. Cotton (crop index 2) — all regions, all years
cotton_all = yields[:, 2, :]
print("\n4. Cotton all regions/years shape:", cotton_all.shape)
print(cotton_all.round(0))

# 5. KPK (index 2), Rice (index 1), 2021 (index 2)
val = yields[2, 1, 2]
print(f"\n5. KPK Rice 2021: {val:,.1f} thousand tonnes")

1. shape: (8, 4, 5), ndim: 3, size: 160, dtype: float64

2. Punjab data shape: (4, 5)
[[22093. 21459. 22620. 19888. 22560.]
 [ 3840.  3677.  3524.  4098.  3500.]
 [ 9597.  9563.  9020.  9191.  9831.]
 [66863. 73157. 68266. 63579. 71409.]]

3. Wheat yields 2023 (all regions):
   Punjab                : 22,560 kt
   Sindh                 : 4,420 kt
   KPK                   : 996 kt
   Balochistan           : 1,124 kt
   Gilgit-Baltistan      : 77 kt
   AJK                   : 49 kt
   FATA                  : 31 kt
   ICT                   : 5 kt

4. Cotton all regions/years shape: (8, 5)
[[9.597e+03 9.563e+03 9.020e+03 9.191e+03 9.831e+03]
 [2.923e+03 2.957e+03 3.088e+03 2.890e+03 2.969e+03]
 [1.000e+01 1.000e+01 1.000e+01 1.100e+01 1.100e+01]
 [9.120e+02 7.840e+02 8.250e+02 7.890e+02 9.010e+02]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [2.000e+00 2.000e+00 2.000e+00 2.000e+00 2.000e+00]
 [1.000e+00 1.000e+00 1.000e+00 1.00

### Q32 - National totals with axis-based aggregation (1 mark)

Use **axis-based aggregation** (no loops) for all questions.

1. Compute **total national production per crop per year**: sum across regions (axis=0).  
   Shape should be (4, 5). Print a formatted table: crops as rows, years as columns.

2. Compute **total production per region across all crops and years**:  
   sum across both crops (axis=1) and years (axis=2). Shape: (8,).  
   Which region is the largest producer? Print name and total.

3. Compute **average yield per crop** across all regions and all years.  
   Shape: (4,). Print crop name --> average yield.

4. Find the single **highest-yielding (region, crop, year) combination**.  
   Use `np.argmax()` on the flat array, then `np.unravel_index()` to recover the 3D index.  
   Print: 'Highest yield: [region] [crop] [year] = [value] thousand tonnes'.

In [135]:
# Q32 - your answer here
# 1. National total per crop per year — sum across regions (axis=0)
national = yields.sum(axis=0)   # shape (4, 5)
print("1. National production (thousand tonnes) — rows=crops, cols=years:")
print(f"{'':12}", end="")
for y in years: print(f"{y:>10}", end="")
print()
for c, row in zip(crops, national):
    print(f"{c:<12}", end="")
    for v in row: print(f"{v:>10,.0f}", end="")
    print()

# 2. Total per region across ALL crops and years
region_totals = yields.sum(axis=(1, 2))   # sum over crops and years
top_idx = np.argmax(region_totals)
print(f"\n2. Largest producer: {regions[top_idx]} ({region_totals[top_idx]:,.0f} kt)")

# 3. Average yield per crop across all regions and years
crop_avg = yields.mean(axis=(0, 2))   # mean over regions and years
print("\n3. Average yield per crop:")
for c, v in zip(crops, crop_avg):
    print(f"   {c:<12}: {v:,.0f} kt")

# 4. Single highest (region, crop, year) combination
flat_max_idx = np.argmax(yields)
r_i, c_i, y_i = np.unravel_index(flat_max_idx, yields.shape)
print(f"\n4. Highest yield: {regions[r_i]} {crops[c_i]} {years[y_i]} = "
      f"{yields[r_i, c_i, y_i]:,.0f} thousand tonnes")

1. National production (thousand tonnes) — rows=crops, cols=years:
                  2019      2020      2021      2022      2023
Wheat           28,304    27,864    28,981    26,401    29,262
Rice             6,975     7,002     6,602     6,749     6,585
Cotton          13,446    13,317    12,945    12,884    13,715
Sugarcane       86,182    95,187    89,285    83,283    93,435

2. Largest producer: Punjab (517,734 kt)

3. Average yield per crop:
   Wheat       : 3,520 kt
   Rice        : 848 kt
   Cotton      : 1,658 kt
   Sugarcane   : 11,184 kt

4. Highest yield: Punjab Sugarcane 2020 = 73,157 thousand tonnes


### Q33 - Year-on-year growth rate (1 mark)

Agricultural planners need to know if production is growing or declining.

1. Compute the **year-on-year growth rate** for each region × crop pair:  
   `growth = (yields[:, :, 1:] - yields[:, :, :-1]) / yields[:, :, :-1] * 100`  
   Print the shape of `growth` - should be (8, 4, 4): 4 growth rates for 5 years.

2. Which (region, crop) pair had the **largest single-year growth** across all years?  
   Use `np.argmax()` + `np.unravel_index()`. Print the combination and the growth %.

3. Which (region, crop) pair had the **largest single-year decline**?  
   Use `np.argmin()`. Print combination and the decline %.

4. Compute average annual growth per crop across all regions and all year-pairs.  
   Which crop is growing fastest on average? Which is declining?

In [140]:
# Q33 - your answer here
# 1. Year-on-year growth rates
growth = (yields[:, :, 1:] - yields[:, :, :-1]) / yields[:, :, :-1] * 100
print("1. Growth array shape:", growth.shape)   # (8, 4, 4)

# 2. Largest single-year growth
flat_max = np.argmax(growth)
ri, ci, yi = np.unravel_index(flat_max, growth.shape)
print(f"\n2. Largest growth : {regions[ri]} {crops[ci]} "
      f"{years[yi]}-->{years[yi+1]}: +{growth[ri,ci,yi]:.1f}%")

# 3. Largest single-year decline
flat_min = np.argmin(growth)
ri2, ci2, yi2 = np.unravel_index(flat_min, growth.shape)
print(f"3. Largest decline: {regions[ri2]} {crops[ci2]} "
      f"{years[yi2]}-->{years[yi2+1]}: {growth[ri2,ci2,yi2]:.1f}%")

# 4. Average growth per crop (mean over regions and year-pairs)
avg_growth = growth.mean(axis=(0, 2))   # shape (4,)
print("\n4. Average annual growth per crop:")
for c, g in zip(crops, avg_growth):
    trend = "growing" if g > 0 else "declining"
    print(f"   {c:<12}: {g:+.2f}% ({trend})")

1. Growth array shape: (8, 4, 4)

2. Largest growth : Gilgit-Baltistan Cotton 2019-->2020: +nan%
3. Largest decline: Gilgit-Baltistan Cotton 2019-->2020: nan%

4. Average annual growth per crop:
   Wheat       : +0.94% (growing)
   Rice        : +0.73% (growing)
   Cotton      : +nan% (declining)
   Sugarcane   : +0.30% (growing)


C:\Users\LUQMAN\AppData\Local\Temp\ipykernel_14092\3066734818.py:3: RuntimeWarning: invalid value encountered in divide
  growth = (yields[:, :, 1:] - yields[:, :, :-1]) / yields[:, :, :-1] * 100


### Q34 - Broadcasting for target comparison (1 mark)

The government has set **annual production targets** (thousand tonnes):
```python
targets = np.array([22000.0, 4000.0, 10000.0, 72000.0])  # Wheat, Rice, Cotton, Sugarcane
```

1. Compute total national production per crop per year (sum across regions, axis=0).  
   Shape: (4, 5). Call it `national`.

2. Use broadcasting to compute `shortfall = targets[:, np.newaxis] - national`.  
   Print shape (should be 4×5). Positive = below target; Negative = above target.

3. Using a boolean mask, print which (crop, year) combinations **met or exceeded** the target.

4. For each crop, print how many of the 5 years the target was met.

5. Compute `achievement_pct = national / targets[:, np.newaxis] * 100`.  
   Print for each crop and year, rounded to 1 decimal place.

In [141]:
# Q34 - your answer here
targets = np.array([22000.0, 4000.0, 10000.0, 72000.0])


# 1. National per crop per year
national = yields.sum(axis=0)   # (4, 5)

# 2. Broadcasting shortfall — targets is (4,), national is (4,5)
shortfall = targets[:, np.newaxis] - national   # (4,5)
print(f"2. Shortfall matrix shape: {shortfall.shape}")

# 3. (crop, year) combinations that met/exceeded target
met = shortfall <= 0
print("\n3. Target met (crop, year):")
for ci, yi in zip(*np.where(met)):
    print(f"   {crops[ci]} {years[yi]}: "
          f"produced {national[ci,yi]:,.0f} vs target {targets[ci]:,.0f}")

# 4. Count years target met per crop
print("\n4. Years target met per crop:")
for c, row in zip(crops, met):
    print(f"   {c:<12}: {row.sum()} / {len(years)}")

# 5. Achievement percentage
ach_pct = national / targets[:, np.newaxis] * 100
print("\n5. Achievement % (rows=crops, cols=years):")
print(f"{'':12}", end="")
for y in years: print(f"{y:>8}", end="")
print()
for c, row in zip(crops, ach_pct):
    print(f"{c:<12}", end="")
    for v in row: print(f"{v:>7.1f}%", end="")
    print()

2. Shortfall matrix shape: (4, 5)

3. Target met (crop, year):
   Wheat 2019: produced 28,304 vs target 22,000
   Wheat 2020: produced 27,864 vs target 22,000
   Wheat 2021: produced 28,981 vs target 22,000
   Wheat 2022: produced 26,401 vs target 22,000
   Wheat 2023: produced 29,262 vs target 22,000
   Rice 2019: produced 6,975 vs target 4,000
   Rice 2020: produced 7,002 vs target 4,000
   Rice 2021: produced 6,602 vs target 4,000
   Rice 2022: produced 6,749 vs target 4,000
   Rice 2023: produced 6,585 vs target 4,000
   Cotton 2019: produced 13,446 vs target 10,000
   Cotton 2020: produced 13,317 vs target 10,000
   Cotton 2021: produced 12,945 vs target 10,000
   Cotton 2022: produced 12,884 vs target 10,000
   Cotton 2023: produced 13,715 vs target 10,000
   Sugarcane 2019: produced 86,182 vs target 72,000
   Sugarcane 2020: produced 95,187 vs target 72,000
   Sugarcane 2021: produced 89,285 vs target 72,000
   Sugarcane 2022: produced 83,283 vs target 72,000
   Sugarcane 2023: 

### Q35 - Punjab dominance analysis (1 mark)

Punjab is Pakistan's agricultural heartland. Quantify its contribution.

1. Extract Punjab's yields: `punjab = yields[0]` - shape (4, 5).
2. Compute national totals per crop per year: sum across regions (axis=0) - shape (4, 5).
3. Compute `punjab_share = punjab / national * 100`.  
   Print Punjab's share (%) for each crop in each year. Round to 1 decimal place.
4. Find: which crop has the highest average Punjab share? Print crop name and mean %.
5. In which year did Punjab's share of **wheat production** dip the lowest?  
   Print year and share %.

In [142]:
# Q35 - your answer here
punjab  = yields[0]                     # (4, 5)
national = yields.sum(axis=0)           # (4, 5)

# 3. Punjab share %
punjab_share = punjab / national * 100  # (4, 5)
print("Punjab share % (rows=crops, cols=years):")
print(f"{'':12}", end="")
for y in years: print(f"{y:>8}", end="")
print()
for c, row in zip(crops, punjab_share):
    print(f"{c:<12}", end="")
    for v in row: print(f"{v:>7.1f}%", end="")
    print()

# 4. Highest average Punjab share
avg_share = punjab_share.mean(axis=1)   # mean over years
top_crop_idx = np.argmax(avg_share)
print(f"\n4. Highest avg Punjab share: {crops[top_crop_idx]} ({avg_share[top_crop_idx]:.1f}%)")

# 5. Year with lowest Punjab wheat share
wheat_share = punjab_share[0]           # Wheat is index 0
min_year_idx = np.argmin(wheat_share)
print(f"5. Lowest Punjab wheat share: {years[min_year_idx]} ({wheat_share[min_year_idx]:.1f}%)")

Punjab share % (rows=crops, cols=years):
                2019    2020    2021    2022    2023
Wheat          78.1%   77.0%   78.0%   75.3%   77.1%
Rice           55.1%   52.5%   53.4%   60.7%   53.2%
Cotton         71.4%   71.8%   69.7%   71.3%   71.7%
Sugarcane      77.6%   76.9%   76.5%   76.3%   76.4%

4. Highest avg Punjab share: Wheat (77.1%)
5. Lowest Punjab wheat share: 2022 (75.3%)


### Q36 - Drought impact detection (1 mark)

We deliberately introduced a drought in Balochistan (2022) and floods in Sindh (2022).
Can you detect them from the data alone?

1. For each region × crop pair, compute the **5-year mean** and **std** of yields.  
   Shapes both (8, 4).
2. Compute **z-scores** for every yield value:  
   `z = (yields - mean[:,:,None]) / std[:,:,None]` using broadcasting.  
   Print the z-score for Balochistan-Wheat-2022.
3. Flag all values with `z < -1.5` as **anomalously low** (potential drought/flood).  
   Print the (region, crop, year) of every anomaly detected.
4. Were both injected anomalies (Balochistan Wheat 2022, Sindh Rice 2022) detected?  
   Print `True` for each if it appeared in the anomaly list.

In [143]:
# Q36 - your answer here
# 1. Per region-crop 5-year mean and std
mean_rc = yields.mean(axis=2)   # (8, 4)
std_rc  = yields.std(axis=2)    # (8, 4)
print("mean shape:", mean_rc.shape, "  std shape:", std_rc.shape)

# 2. Z-scores — broadcasting: mean/std are (8,4), yields is (8,4,5)
z = (yields - mean_rc[:, :, np.newaxis]) / (std_rc[:, :, np.newaxis] + 1e-9)

# Balochistan=index 3, Wheat=index 0, 2022=index 3
print(f"\n2. Balochistan Wheat 2022 z-score: {z[3, 0, 3]:.3f}")

# 3. Flag anomalously low values (z < -1.5)
print("\n3. Anomalies detected (z < -1.5):")
for ri, ci, yi in zip(*np.where(z < -1.5)):
    print(f"   {regions[ri]:<22} {crops[ci]:<12} {years[yi]}  z={z[ri,ci,yi]:.3f}")

# 4. Were injected anomalies caught?
baloch_wheat_caught = z[3, 0, 3] < -1.5
sindh_rice_caught   = z[1, 1, 3] < -1.5
print(f"\n4. Balochistan Wheat 2022 detected: {baloch_wheat_caught}")
print(f"   Sindh Rice 2022 detected        : {sindh_rice_caught}")

mean shape: (8, 4)   std shape: (8, 4)

2. Balochistan Wheat 2022 z-score: -1.799

3. Anomalies detected (z < -1.5):
   Punjab                 Wheat        2022  z=-1.822
   Punjab                 Sugarcane    2022  z=-1.504
   Sindh                  Rice         2022  z=-1.814
   KPK                    Wheat        2020  z=-1.845
   KPK                    Sugarcane    2023  z=-1.718
   Balochistan            Wheat        2022  z=-1.799
   Balochistan            Sugarcane    2022  z=-1.672
   Gilgit-Baltistan       Wheat        2023  z=-1.657
   AJK                    Wheat        2022  z=-1.621
   FATA                   Wheat        2021  z=-1.713
   FATA                   Rice         2021  z=-1.552
   FATA                   Cotton       2023  z=-1.974
   ICT                    Wheat        2022  z=-1.886

4. Balochistan Wheat 2022 detected: True
   Sindh Rice 2022 detected        : True


### Q37 - Rank regions by 2023 performance (1 mark)

For strategic investment planning, the government wants regions ranked by
total agricultural output in the most recent year (2023).

1. Extract all yields for 2023: `yields_2023 = yields[:, :, -1]` - shape (8, 4).
2. Compute each region's **total production in 2023** across all 4 crops: shape (8,).
3. Use `np.argsort()` to rank regions from **highest to lowest** total production.
4. Print a ranked table:
   ```
   Rank 1: Punjab     - 102,450.3 thousand tonnes
   Rank 2: Sindh      -  29,214.7 thousand tonnes
   ...
   ```
5. Compute each region's **percentage share** of total national 2023 output.
   Print alongside the ranking table.

In [144]:
# Q37 - your answer here
# 1. 2023 yields (last year, index 4)
yields_2023 = yields[:, :, -1]   # (8, 4)

# 2. Total per region in 2023
totals_2023 = yields_2023.sum(axis=1)   # (8,)

# 3. Rank descending
rank_idx = np.argsort(totals_2023)[::-1]

# 4 & 5. Ranked table with share
national_2023 = totals_2023.sum()
print("2023 Regional Production Ranking")
print("=" * 55)
print(f"{'Rank':<6} {'Region':<24} {'Total (kt)':>12} {'Share':>8}")
print("-" * 55)
for rank, idx in enumerate(rank_idx):
    share = totals_2023[idx] / national_2023 * 100
    print(f"  {rank+1:<4} {regions[idx]:<24} {totals_2023[idx]:>12,.0f} {share:>7.1f}%")

2023 Regional Production Ranking
Rank   Region                     Total (kt)    Share
-------------------------------------------------------
  1    Punjab                        107,300    75.0%
  2    Sindh                          30,406    21.3%
  3    Balochistan                     3,426     2.4%
  4    KPK                             1,514     1.1%
  5    AJK                               127     0.1%
  6    Gilgit-Baltistan                  122     0.1%
  7    FATA                               83     0.1%
  8    ICT                                19     0.0%


### Q38 - Crop diversification index (1 mark)

A region that produces only one crop is economically vulnerable.
The **Herfindahl-Hirschman Index (HHI)** measures concentration:

$$\text{HHI} = \sum_{c=1}^{4} \left(\frac{\text{yield}_c}{\text{total yield}}\right)^2$$

HHI close to 1.0 = highly concentrated (bad); close to 0.25 = well diversified.

1. Compute each region's **total yield across all crops and all years**: shape (8,).
2. Compute each region's **per-crop total** across all years: shape (8, 4).
3. Compute crop **share** per region: `share = per_crop_total / total_all[:, None]`.  
   Verify each row sums to 1.0.
4. Compute HHI per region: `hhi = (share**2).sum(axis=1)`. Print.
5. Rank regions from most diversified (lowest HHI) to least diversified (highest HHI).  
   Which region is most at risk from a single-crop failure?

In [146]:
# Q38 - your answer here
# 1. Total per region across ALL crops and years
total_all = yields.sum(axis=(1, 2))   # (8,)

# 2. Per-crop total per region (sum over years)
per_crop_total = yields.sum(axis=2)   # (8, 4)

# 3. Crop share per region
share = per_crop_total / total_all[:, np.newaxis]   # (8,4)
print("3. Row sums (should all be 1.0):", share.sum(axis=1).round(6))

# 4. HHI per region
hhi = (share ** 2).sum(axis=1)   # (8,)
print("\n4. HHI per region:")
for r, h in zip(regions, hhi):
    print(f"   {r:<22}: {h:.4f}")

# 5. Rank from most diversified (lowest HHI) to least
rank_idx = np.argsort(hhi)
print("\n5. Diversification ranking (most --> least):")
for rank, idx in enumerate(rank_idx):
    print(f"   {rank+1}. {regions[idx]:<22} HHI={hhi[idx]:.4f}")

most_at_risk = regions[np.argmax(hhi)]
print(f"\nMost at risk from single-crop failure: {most_at_risk}")

3. Row sums (should all be 1.0): [1. 1. 1. 1. 1. 1. 1. 1.]

4. HHI per region:
   Punjab                : 0.4932
   Sindh                 : 0.4738
   KPK                   : 0.4840
   Balochistan           : 0.3058
   Gilgit-Baltistan      : 0.4844
   AJK                   : 0.3866
   FATA                  : 0.3741
   ICT                   : 0.4037

5. Diversification ranking (most --> least):
   1. Balochistan            HHI=0.3058
   2. FATA                   HHI=0.3741
   3. AJK                    HHI=0.3866
   4. ICT                    HHI=0.4037
   5. Sindh                  HHI=0.4738
   6. KPK                    HHI=0.4840
   7. Gilgit-Baltistan       HHI=0.4844
   8. Punjab                 HHI=0.4932

Most at risk from single-crop failure: Punjab


### Q39 - 5-year moving average trend (1 mark)

A moving average smooths out short-term fluctuations to reveal trends.
Since we only have 5 years, compute the overall trajectory using vectorised ops.

1. Compute national total per crop per year: `national = yields.sum(axis=0)` - shape (4, 5).

2. For each crop, compute the **year-by-year change** (2020-2019, 2021-2020, etc.):  
   `changes = national[:, 1:] - national[:, :-1]` - shape (4, 4).

3. Compute the **average annual change** per crop over the 5-year period.
   Print: which crops are on an upward trend and which are declining?

4. Compute each crop's **coefficient of variation** (std/mean × 100) across the 5 years.  
   A high CV indicates an unstable, volatile crop. Print CV % per crop, ranked highest to lowest.

5. If the 2024 yield were extrapolated using `2023_yield + avg_annual_change`,  
   what would national production be per crop? Print the 2024 projections.

In [147]:
# Q39 - your answer here
# 1. National total per crop per year
national = yields.sum(axis=0)   # (4, 5)

# 2. Year-on-year changes
changes = national[:, 1:] - national[:, :-1]   # (4, 4)

# 3. Average annual change per crop
avg_change = changes.mean(axis=1)   # (4,)
print("3. Average annual change per crop:")
for c, ch in zip(crops, avg_change):
    trend = "upward" if ch > 0 else "declining"
    print(f"   {c:<12}: {ch:+,.0f} kt/year ({trend})")

# 4. Coefficient of variation per crop
cv = national.std(axis=1) / national.mean(axis=1) * 100
rank_cv = np.argsort(cv)[::-1]
print("\n4. Coefficient of variation (most volatile first):")
for idx in rank_cv:
    print(f"   {crops[idx]:<12}: CV = {cv[idx]:.2f}%")

# 5. 2024 projections
proj_2024 = national[:, -1] + avg_change
print("\n5. 2024 national production projections:")
for c, p in zip(crops, proj_2024):
    print(f"   {c:<12}: {p:,.0f} thousand tonnes")

3. Average annual change per crop:
   Wheat       : +239 kt/year (upward)
   Rice        : -97 kt/year (declining)
   Cotton      : +67 kt/year (upward)
   Sugarcane   : +1,813 kt/year (upward)

4. Coefficient of variation (most volatile first):
   Sugarcane   : CV = 4.94%
   Wheat       : CV = 3.58%
   Rice        : CV = 2.62%
   Cotton      : CV = 2.35%

5. 2024 national production projections:
   Wheat       : 29,501 thousand tonnes
   Rice        : 6,488 thousand tonnes
   Cotton      : 13,782 thousand tonnes
   Sugarcane   : 95,248 thousand tonnes


### Q40 - Full pipeline: food security score (1 mark)

Design and compute a **Food Security Score** for each region.
This is an open-ended question - your pipeline will be evaluated on correctness
of the NumPy operations, not on the policy choice of weights.

**Required steps:**

1. **Scale** each crop's 5-year total yield for each region to [0, 1] using min-max  
   across all 8 regions (axis=0 after summing over years).

2. **Weight** the crops. Wheat is the staple food in Pakistan. Use weights of your choice  
   but they must sum to 1.0. Define them as a NumPy array and document your reasoning  
   in a comment.

3. Compute the **weighted Food Security Score** for each region using a single  
   `np.dot()` or broadcasting expression. Shape: (8,).

4. Print a **final ranked table** from most food-secure to least food-secure:
   ```
   Food Security Ranking - Pakistan Regions 2019–2023
   =====================================================
   Rank 1: Punjab            Score: 0.918
   Rank 2: Sindh             Score: 0.543
   ...
   ```

5. Write **3 sentences** (as Python comments) interpreting the ranking:
   - Which region is most food-secure and why does that make sense?
   - Which region is most vulnerable and what policy intervention might help?
   - What are the limitations of this index (what factors does it NOT capture)?

In [ ]:
# Q40 - your answer here
# Define your weights here (must sum to 1.0)
# weights = np.array([w_wheat, w_rice, w_cotton, w_sugarcane])
# Wheat is the primary staple, highest weight
# Rice and Sugarcane are important cash/food crops
# Cotton is mainly a cash/export crop, less direct food security impact

weights = np.array([0.40, 0.25, 0.10, 0.25])   # Wheat, Rice, Cotton, Sugarcane
print("Weights:", dict(zip(crops, weights)))
print("Sum:", weights.sum())

# 1. 5-year total per region per crop
per_crop_5yr = yields.sum(axis=2)   # (8, 4)

# Min-max scale each crop across regions (axis=0)
col_min = per_crop_5yr.min(axis=0)
col_max = per_crop_5yr.max(axis=0)
scaled  = (per_crop_5yr - col_min) / (col_max - col_min)   # (8, 4)

# 3. Weighted Food Security Score
fss = (scaled * weights).sum(axis=1)   # (8,)  — broadcasting (8,4) * (4,) -> (8,4) -> sum -> (8,)

# 4. Ranked table
rank_idx = np.argsort(fss)[::-1]
print("\nFood Security Ranking — Pakistan Regions 2019–2023")
print("=" * 50)
for rank, idx in enumerate(rank_idx):
    bar = "█" * int(fss[idx] * 30)
    print(f"  Rank {rank+1}: {regions[idx]:<22} {fss[idx]:.3f}  {bar}")

# 5. Interpretation (3 sentences):
# Punjab ranks #1 because it produces the overwhelming majority of both wheat and
# sugarcane - Pakistan's two highest-weight crops - dwarfing all other regions.
# Gilgit-Baltistan and AJK rank at the bottom due to minimal flatland agriculture;
# policy interventions should focus on improving food distribution networks and
# alternative nutrition sources (livestock, horticulture) rather than crop expansion.
# Limitations: this index captures production volume only - it ignores population size
# (per-capita availability), food affordability, storage losses, import dependency,
# and dietary diversity, all of which are critical components of true food security.

Weights: {np.str_('Wheat'): np.float64(0.4), np.str_('Rice'): np.float64(0.25), np.str_('Cotton'): np.float64(0.1), np.str_('Sugarcane'): np.float64(0.25)}
Sum: 1.0

Food Security Ranking — Pakistan Regions 2019–2023
  Rank 1: Punjab                 1.000  ██████████████████████████████
  Rank 2: Sindh                  0.359  ██████████
  Rank 3: Balochistan            0.046  █
  Rank 4: KPK                    0.027  
  Rank 5: Gilgit-Baltistan       0.002  
  Rank 6: AJK                    0.002  
  Rank 7: FATA                   0.001  
  Rank 8: ICT                    0.000  


## Submission Checklist

Before submitting, confirm:

- [ ] All 40 questions have a non-empty code cell below them
- [ ] Every code cell produces labelled output (unlabelled output = half marks)
- [ ] Q5, Q23, Q28, Q30, Q38, Q40 include at least one comment explaining a concept
- [ ] The dataset cells (before Part B and before Part D) were run before their sections

**Marking scheme:**
- Correct output: 0.5 marks
- Correct method (using the concept taught): 0.4 marks
- Comment / interpretation where asked: 0.1 marks

**Name:** Muhammad Lukman (*Instructor*)  

**Submission Date:** 24/07/2026

*Good luck.*